server.port=8082
spring.application.name=order-activity-service

spring.cassandra.contact-points=127.0.0.1:9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=ecommerce_orders
spring.cassandra.schema-action=NONE

management.endpoints.web.exposure.include=health,info,metrics